secret:
  data: local

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testdb.cwvhqcq8efz1.ap-northeast-2.rds.amazonaws.com:3306/testdb?serverTimezone=UTC
    username: admin
    password: karrotmarket